% Insert buttons to play, pause the videos.
function insertButtons(hFig,hAxes,settings)

    % Play button with text Start/Pause/Continue
    uicontrol(hFig,'unit','pixel',...
              'style','pushbutton',...
              'string','Start',...
              'Units','Normalized',...
              'position',settings.buttonPos.start,...
              'tag','PBButton123',...
              'callback', {@playCallback,hAxes,settings});

    % Exit button with text Exit
    uicontrol(hFig,'unit','pixel',...
                   'style','pushbutton',...
                   'string','Exit',...
                   'Units','Normalized',...
                   'position',settings.buttonPos.exit,...
                   'callback', {@exitCallback,hFig});
        
    % Reset button with text Reset
    uicontrol(hFig,'unit','pixel',...
                   'style','pushbutton',...
                   'string','Reset',...
                   'Units','Normalized',...
                   'position',settings.buttonPos.reset,...
                   'callback', {@resetCallback,hAxes,settings});

end  